---
#---------------------------------#
#  Build Image                    #
#---------------------------------#
image: Visual Studio 2019

#---------------------------------#
#  Build Script                   #
#---------------------------------#
build_script:
    - ps: .\build.ps1 -Target ContinuousIntegration

# Tests
test: off

#---------------------------------#
#        Branches to build        #
#---------------------------------#
branches:
    # Whitelist
    only:
        - develop
        - master

#---------------------------------#
#  Build Cache                    #
#---------------------------------#
cache:
    - Tools -> recipe.cake