#---------------------------------#
#      general configuration      #
#---------------------------------#

# version format
version: 1.0.{build}

branches:
  only:
    - master
    - develop

#---------------------------------#
#    environment configuration    #
#---------------------------------#

# clone directory
clone_folder: C:\projects\GitReleaseManager

# environment variables
environment:
  MyGetDevelopApiKey:
    secure: Ddgbcn3J5vLpseoyk7B3yIk7r0lwOBrNdofj0ak23dsWOZq1sMPhtwWpt5oTA1jm
  MyGetDevelopFeedUrl: https://www.myget.org/F/grm_develop/
  MyGetMasterApiKey:
    secure: 4I1Xep3sy2ybI89tiqzcK385wIKnt0D4p9JM5sb+ap86kSyfzxxj6nFaO7AUm80H
  MyGetMasterFeedUrl: https://www.myget.org/F/grm_master/
  ChocolateyApiKey:
    secure: 2Sbie8uhFjl1v+NtLuR1oGcWnQE2M87jq0fSEwFOYcnNEC5qdwCkgVOG0MmC2Ffv
  ChocolateyFeedUrl: https://chocolatey.org/
  NugetApiKey:
    secure: a/xbTgIAc+QGdAwANmenmrUJFG5hqB+jMyqB6y80KZYXfRHOVEB+1dB4CEyDednf
  NugetFeedUrl: https://nuget.org/
  GitHubUserName:
    secure: 9zbEIVfl69s/qhei6qkdeA==
  GitHubPassword:
    secure: XSuLygmr83zEpWcXIXMXGocN0QbooLud1eIMA3mQWKkT9LAU4TyrijLBcJIo7bD7
  CoverityProjectToken:
    secure: v9LYg/tMc/XFYAiIJl+KiGpo1pBtyQgcANoNqra/5qg=
  CoverityEmailDistribution:
    secure: FuJy6Wqvw19/VBYyE0hHY+lNbkKxlN1Jsr8OiTdAgkQ=
  COVERALLS_REPO_TOKEN:
    secure: Z5cvhf8uoT2AqN/yfurbwty0RwNMSZA6l+nhINv+uNxVbdCkBDyPjeFUCNCnujs3
   
#---------------------------------#
#       build configuration       #
#---------------------------------#

build_script:
  - ps: .\BuildScripts\build.ps1
  
test: off

#---------------------------------#
#      caching configuration      #
#---------------------------------#

cache:
  - Source\packages

#---------------------------------#
#  notifications configuration    #
#---------------------------------#
notifications:
  - provider: Webhook
    url: https://webhooks.gitter.im/e/a72ea926ecc08de68e71
    on_build_success: true
    on_build_failure: true
    on_build_status_changed: true
