#---------------------------------#
#      general configuration      #
#---------------------------------#

# version format
version: 1.0.{build}

branches:
  only:
    - master
    - develop

#---------------------------------#
#    environment configuration    #
#---------------------------------#

# clone directory
clone_folder: C:\projects\GitReleaseManager

# environment variables
environment:
  MyGetDevelopApiKey:
    secure: KFeZCL5TKhJaL96tl0H+HjcVYv/cSsVtFE48mYOpmCMuuNH/sId04odoavJqgl7f
  MyGetDevelopFeedUrl: https://www.myget.org/F/packages_develop/
  MyGetMasterApiKey:
    secure: OewKlbHSmiVUj7kC0WMZwvjDQKBjcZNgSYyXIxDNGZxssxx4KDQNyRbT+6PZ+uPH
  MyGetMasterFeedUrl: https://www.myget.org/F/packages_master/
  ChocolateyApiKey:
    secure: rGZLB7/BIEUl7XMeMeidRD50lQe8igKyPUJSAzFBd146Foc67Vyagv1kJ4ImTGvY
  ChocolateyFeedUrl: https://chocolatey.org/
  NugetApiKey:
    secure: a/xbTgIAc+QGdAwANmenmrUJFG5hqB+jMyqB6y80KZYXfRHOVEB+1dB4CEyDednf
  NugetFeedUrl: https://nuget.org/
  GitHubUserName:
    secure: je/D8MZcaA0IMfIhmrqShQ==
  GitHubPassword:
    secure: DCLeGjj/fPf/rkF2y4e3ZEFta2Efnzof1GiOEIPdhw0PQs4NBnjaENwif1itJB96
  CoverityProjectToken:
    secure: sNjhk2dFsZr+aR38o8Gd8Lmg09HrEvA7694/Ab339mc=
  CoverityEmailDistribution:
    secure: aUKSmixrP4rsyYLhnPvZY3sJoDp6J3W19tE3aTOkI2A=
  COVERALLS_REPO_TOKEN:
    secure: Nq9nxGOJfq4uTLPaPXiYl32/cVsa/PtPE3ptDbSDjNbEpRRloH9KHjba/B+Oh6yx
   
#---------------------------------#
#       build configuration       #
#---------------------------------#

build_script:
  - ps: .\BuildScripts\build.ps1
  
test: off

#---------------------------------#
#      caching configuration      #
#---------------------------------#

cache:
  - Source\packages

#---------------------------------#
#  notifications configuration    #
#---------------------------------#
notifications:
  - provider: Webhook
    url: https://webhooks.gitter.im/e/a72ea926ecc08de68e71
    on_build_success: true
    on_build_failure: true
    on_build_status_changed: true
